[package]
name = "mz16"
version = "0.1.1"
authors = ["Jacob Salzberg"]
edition = "2018"
description = "A library for reading dos 16 bit executables of the mz format."
license = "GPL-2.0-only"

[dependencies]
byteorder = "1.3.1"