[package]
name = "mz16"
version = "0.1.2"
authors = ["Jacob Salzberg"]
edition = "2018"
description = "A library for reading dos 16 bit executables of the mz format."
license = "MIT"

[dependencies]
byteorder = "1.3.1"